sudo: false
language: node_js

node_js:
  - 0.12
  - 4.0
  - 4.1
  - 4.2

before_install:
  - npm install -g gulp
  - npm install

script:
  - gulp ci

matrix:
  allow_failures:
    - node_js: 4.0

deploy:
  provider: npm
  email: "john@radify.io"
  api_key:
    secure: "KP2ktSoNArc01Fvt9/4feIggTA8UxbnH64zMBPiQcKTMlkNCqwDOeeMA+os/fb7Yz1yZ9pRSM+MoUcphav3ykLTN+PqMiQ7BUpo9HMh58zH9SxvtP3LAn1hQOO3tarBfiVb8flrloyrXxrhKPXkYJckTPoJF/fx8ZzId0qMHbj4WhVx1Y1pGZdtqbEb8EJfHIs69e4AZLK3P2KA41omPyH+jhEbbC9MozKX0Z23SwmJQHqgUEipbYG0bAILD/A+j4C7LgHvh8wuqLu1XZfWkozJjNGqqOjcb1M6yaB90NzbBLhXDXjwHA+Fke5IaCfNY4F6FSqtYcgPf2BWQ0S4Pp9BvtD4e/qmDP7XYqiMIeGBuy/t8qT/rg3WX/nScCfSocDH1/+/5Zd78jdUYeFwVguPvihgfNFxNflCxg1Kzq09CuzvjAx/oc7PFm2GeDwq204+VFdQsOBSPJwEmlbSfozbRRtlSYQ4yPeA5Yw3o97V0kd7ZIG3r4GcyuMsSpMgfXv7GBNI4y5DDefnfJU0iLNiWJ21WatiUNLTxM1PRFfuMy05I22rwjYY5YQMEAi42/yQKhDABLk7rXjgpo7OML15ppxBswX8chV5ltGy+vKmtCAr7MCHo6PnK/Pj0g6aXYSwjnZhG391hZhJkn0LNLJzpD592na6zJEHYjpcf/VU="
  on:
    tags: true
    branch: master

addons:
  code_climate:
    repo_token:
      secure: "DghCDrb9S1u/ylCedrGNH+fnSsiffM3eNOqDD3H7FVHIyLR/bVVJ3oGSwo2c+nQijqOnxzwGMRh1C/I9fwFOFeb6frVWr6avaIn7UXhbZNvCmLcKnJQzesvk2DrkeCsaAfBMg3MPHwSbqC+tNv2RkvsKpk2ijQChNzcFeJmKrjTz0RCz8hTQdN2kY8rlak6WKFx/JyUGCFYWYyGRiWq5OumprGW2P/Q+FIrp8Uc3XG/fX84fQ20iuF+tyA0gNhmPMDkHgVCho/14wUV6mvdWgZinGn1H4tHSIZCYPyLYtnl3YqjsHzUg7BqDkR92p7wIQt3jLyV/ncmSknvgTzerdV6N/pWFRokDkTnzxQ6e2ltSY4cBzmxQs8RM62+cTxdU8YruuCzbMdP6pjLyftaItpfO48U"
